[colors]
ansi = [
    "#7a828e", # Black
    "#ff9492", # Red
    "#26cd4d", # Green
    "#f0b72f", # Yellow
    "#2792ff", # Blue, darker and more visible than 0x71b7ff
    "#cb9eff", # Magenta
    "#39c5cf", # Cyan
    "#d9dee3", # White
]
brights = [
    "#9ea7b3",
    "#ffb1af",
    "#4ae168",
    "#f7c843",
    "#91cbff",
    "#cb9eff",
    "#39c5cf",
    "#d9dee3",
]

# background = "#0a0c10"
background = "#000000" # Real black
# foreground = "#f0f3f6"
foreground = "#f1f1f1"

cursor_bg = "#f1f1f1"
cursor_border = "#f1f1f1"
cursor_fg = "#303030"

selection_bg = "#f1f1f1"
selection_fg = "#303030"

[colors.indexed]

[metadata]
name = "github-dark-high-contrast"
wezterm_version = "Always"
